DD-418 update taboola JS encode json correct way
dennisinteractive/taboola pull request #1
Opened 2018-08-07 16:04 UTC by jon-edery

2018-08-08 09:32 UTC, jon-edery commented
Once this PR has been reviewed and tested the patch needs to be generated and posted on Drupal.org  project ->  https://www.drupal.org/project/taboola/issues/2991147.

A new release for the module will need to be created.

The make file on the evo site will need to point to the new release.

2018-08-09 10:28 UTC, marcelovani requested changes
I think we should commit this against 7.x-3.x

2018-08-09 12:27 UTC, davidgrayston requested changes

2018-08-09 12:27 UTC, davidgrayston commented on taboola.module
> +  $widget_settings_json = json_encode($widget_settings);
Perhaps we should use drupal_json_encode() here?

2018-08-09 12:39 UTC, davidgrayston commented
@marcelovani depends if this is a breaking change or is backward compatible - looks like it might be ok on 2.x - @jon-edery can we confirm with product/Taboola?

2018-08-09 13:17 UTC, davidgrayston commented on taboola.module
>        "_taboola.push({" . $loader_identifier . ":'auto'});",
@jon-edery can we also `drupal_json_encode()` this?

2018-08-09 13:18 UTC, davidgrayston commented on taboola.module
> +  $widget_settings_json = json_encode($widget_settings);
... it adds `JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT` options

2018-08-09 13:22 UTC, davidgrayston commented on taboola.module
>        "!function (e, f, u) { e.async = 1; e.src = u; f.parentNode.insertBefore(e, f);}",
@jon-edery looks like it's missing the 4th `i` argument and JS that uses is:
```
    if (!document.getElementById(i)){
      e.async = 1;
      e.src = u;
      e.id = i;
      f.parentNode.insertBefore(e, f);
    }
```

2018-08-09 14:21 UTC, jon-edery commented
requested updates added.

2018-08-13 15:20 UTC, jimwills123 approved these changes
all changes made

2018-08-13 15:20 UTC, merged